services:
  postgres:
    image: postgres:17
    container_name: geoname_postgres
    environment:
      POSTGRES_DB: geoname_test
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - ./test/docker-data/postgres:/var/lib/postgresql/data

  adminer:
    image: adminer
    container_name: geoname_adminer
    ports:
      - "8081:8080"
